version: '3.8'
services:
  service:
    image: service:v2
    restart: on-failure
    container_name: service
    environment: 
      - DB_HOST=192.168.7.22
      - BROKER_HOST=192.168.7.22
    ports: 
      - 5020:5020
    volumes: 
      - .:/app/
    command: ['python3', 'main.py']