version: '3.8'
services:
  db:
    image: postgres
    restart: on-failure
    container_name: database
    env_file:
      - db.env
    ports:
      - 5432:5432
  
  service:
    build: .
    volumes: 
      - .:/app
    container_name: service
    ports: 
      - 5000:5000
      - 50200:5020
  
  rabbitmq:
    image: rabbitmq
    env_file: 
      - celeryapp.env
    ports:
      - 5672:5672
      - 15672:15672
  
  workers:
    build:
      context: .
    hostname: workers
    entrypoint: celery
    command: -A celery_app worker --loglevel=DEBUG
