version: '3.8'
services:
  db:
    image: postgres
    restart: on-failure
    container_name: database
    env_file:
      - db.env
    ports:
      - 5432:5432
  
  service:
    build: .
    volumes: 
      - .:/app
    container_name: service
    ports: 
      - 5020:5000
