version: '3.5'
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: database
    env_file:
      - db.env
    ports:
      - 5432:5432
  
  service:
    image: service_server:v1
    container_name: service
    ports: 
      - 5020:5000
