"""AdvGrooming v1

Revision ID: eb9dfc964a14
Revises: 0c5131c17d01
Create Date: 2021-04-28 17:41:40.002048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb9dfc964a14'
down_revision = '0c5131c17d01'
branch_labels = None
depends_on = None


def upgrade():
    grooming_algorithm = postgresql.ENUM('Advanced', 'End to end', name='grooming_algorithm')
    grooming_algorithm.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdvGrooming',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('pt_id', sa.String(), nullable=False),
    sa.Column('tm_id', sa.String(), nullable=False),
    sa.Column('pt_version', sa.Integer(), nullable=False),
    sa.Column('tm_version', sa.Integer(), nullable=False),
    sa.Column('form', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('manager_id', sa.String(), nullable=True),
    sa.Column('with_clustering', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('algorithm', sa.Enum('advanced', 'end_to_end', name='groomingalgorithm'), nullable=False),
    sa.Column('connections', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('lambda_link', sa.Integer(), nullable=False),
    sa.Column('average_lambda_capacity_usage', sa.Float(), nullable=False),
    sa.Column('lightpaths', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Grooming', sa.Column('algorithm', sa.Enum('Advanced', 'End to end', name='grooming_algorithm'), nullable=False))
    op.add_column('GroomingRegister', sa.Column('algorithm', sa.Enum('Advanced', 'End to end', name='grooming_algorithm'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GroomingRegister', 'algorithm')
    op.drop_column('Grooming', 'algorithm')
    op.drop_table('AdvGrooming')
    # ### end Alembic commands ###
